### ISSUE TITLE
libphonenumber-for-php v8 released

### ISSUE THREAD

**Issue by giggsey** [misd-service-development/phone-number-bundle#114]
Hi,

[libphonenumber-for-php v8](https://github.com/giggsey/libphonenumber-for-php/releases/tag/8.0) has been released, and it'll be good for this project to support it going forwards.

The BC changes are:
 - Convert from PSR-0 to PSR-4
 - Remove deprecated `ShortNumberUtil`, use `ShortNumberInfo` instead
 - Deleting deprecated methods in `ShortNumberInfo` that work on strings, instead
   of phone number objects. These have been marked deprecated for months. Any
   users of these methods should call `PhoneNumberUtil::parse` first to create a
   `PhoneNumber` object, and pass this in.
 - Support semicolon as extension character while parsing phone numbers.

**Comment by thewilkybarkid** [comment]
v1.2.0 released
