### ISSUE TITLE
UniqueEntity error

### ISSUE THREAD

**Issue by RicardoSaracino** [misd-service-development/phone-number-bundle#123]
More than likely this is me not doing something correctly but I'm doing this
/**
 * @ORM\Table(name="customer")
 * @ORM\Entity
 * @UniqueEntity("phone")
 */
class Customer
{
	/**
	 * @var string
	 * @ORM\Column(name="phone", type="phone_number", length=35, nullable=true)
	 * @AssertPhoneNumber
	 */
	private $phone;

getting this .. besides this everything is working fine

The class 'libphonenumber\PhoneNumber' was not found in the chain configured namespaces AppBundle\Entity, Tbbc\MoneyBundle\Entity
500 Internal Server Error - MappingException

Stack Trace
in vendor\doctrine\common\lib\Doctrine\Common\Persistence\Mapping\MappingException.php at line 37

**Comment by magarzon** [comment]
This happens (at least in my case) when there is already a phone with that number in the database (i.e. there is a "violation" in the validation), and at the end of the method validate of class [Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php#L165), when it tries to build the violation, it calls a method formatWithIdentifiers in the same class that, as the value of the field is not a string (is a PhoneNumber instance), it thinks is a managed entity and try to get its identifiers, and the exception is thrown when it tries to get doctrine metadata of PhoneNumber, as it's not a Doctrine Entity.

So, the solution should come in the Symfony code itself (if any), and the workaround that I made was to duplicate the UniqueEntityValidator class, and change that formatWithIdentifiers method, adding the checking:

```
private function formatWithIdentifiers(ObjectManager $em, ClassMetadata $class, $value)
    {
        if (!is_object($value) || $value instanceof \DateTimeInterface) {
            return $this->formatValue($value, self::PRETTY_DATE);
        }

        if ($value instanceof PhoneNumber) {
            return $this->formatValue($value, self::OBJECT_TO_STRING);
        }

        // non unique value is a composite PK
        if ($class->getName() !== $idClass = get_class($value)) {
            $identifiers = $em->getClassMetadata($idClass)->getIdentifierValues($value);
        } else {
            $identifiers = $class->getIdentifierValues($value);
        }

        if (!$identifiers) {
            return sprintf('object("%s")', $idClass);
        }

        array_walk($identifiers, function (&$id, $field) {
            if (!is_object($id) || $id instanceof \DateTimeInterface) {
                $idAsString = $this->formatValue($id, self::PRETTY_DATE);
            } else {
                $idAsString = sprintf('object("%s")', get_class($id));
            }

            $id = sprintf('%s => %s', $field, $idAsString);
        });

        return sprintf('object("%s") identified by (%s)', $idClass, implode(', ', $identifiers));
    }
```

And replacing the legacy class by setting this parameter in services.yml, with the value of my class name:

```
parameters:
    doctrine.orm.validator.unique.class: AppBundle\PhoneNumber\Validator\UniqueEntityValidator
```

But I'm take this opportunity to open an issue in the Symfony repository

**Comment by RicardoSaracino** [comment]
got it working here is the commit for reference 
https://github.com/RicardoSaracino/sarasoft/commit/9b497c3d904f61e4886cdd30282f00bdec3fc801

**Comment by ste93cry** [comment]
Just for reference, symfony/symfony#21619 discusses the problem and the proposal to fix it

**Comment by magarzon** [comment]
The bug is fixed and merged, should be available in the v3.2.5 of Symfony (whenever is released)

**Comment by ste93cry** [comment]
We can close this issue, Symfony 3.2.5 with fix has been [released](http://symfony.com/blog/symfony-3-2-5)

**Comment by magarzon** [comment]
Should be closed, I have tested in my own project that had the same issue and it works as expected
