### ISSUE TITLE
Could not load type "Misd\PhoneNumberBundle\Form\Type\PhoneNumberType"

### ISSUE THREAD

**Issue by fabirus** [misd-service-development/phone-number-bundle#129]
please can you help me to resolve this problem?

Thanks you

**Comment by ste93cry** [comment]
Can you please post the code you're using to create the form? Also, are you sure the bundle is loaded in `AppKernel.php`? Which version of Symfony are you using?

**Comment by fabirus** [comment]
i am using symfony 2.7, the bundle is load correctly in kernel, 
`<?php

namespace NumTek\Backend\EmployeBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Doctrine\ORM\EntityRepository;
use libphonenumber\PhoneNumberFormat;
use Misd\PhoneNumberBundle\Form\Type\PhoneNumberType;

class EmployeType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', 'text', array(
                'label' => 'form.required.name',
                'translation_domain' => 'employe',
                'required' => true,
                'attr' => array(
                    'class' => 'form-control'
            )))
            ->add('prenom', 'text', array(
                'label' => 'form.required.prename',
                'translation_domain' => 'employe',
                'required' => true,
                'attr' => array(
                    'class' => 'form-control'
                )))
            ->add('tel', PhoneNumberType::class, array(
                'default_region' => 'GB', 'format' => PhoneNumberFormat::NATIONAL
            ))`

**Comment by xabbuh** [comment]
In Symfony 2.7, you need to reference the form type by its name (i.e. `tel` here) instead of using its FQCN.

**Comment by fabirus** [comment]
thanks you it's ok now

**Comment by xabbuh** [comment]
Can you close the issue then? :)
