### ISSUE TITLE
National format in a form field breaks international numbers

### ISSUE THREAD

**Issue by thewilkybarkid** [misd-service-development/phone-number-bundle#13]
If I have a field like:

``` php
$form->add('with', 'tel', array('constraints' => new PhoneNumber(), 'default_region' => 'GB', 'format' => PhoneNumberFormat::NATIONAL));
```

If I enter `+1 650-253-0000` it's accepted; it's then formatted nationally, turning it into `(650) 253-0000`. Submitting the form again then leads to a `This value is not a valid phone number` and the value is then `6502530000` as it's not recognised as a GB number.

To resolve this, if format is set to national it will need to format numbers that aren't from the default region differently (so it would need something like an `international_format` setting).

**Comment by teohhanhui** [comment]
I believe this was the wrong fix. When the user wants the national format, it means just that, not the out-of-country calling style.
