### ISSUE TITLE
When Phone don't change, the field has updated

### ISSUE THREAD

**Issue by jewome62** [misd-service-development/phone-number-bundle#133]
Hello,

I find this bug with Loggable in Doctrine Extension:
If I have a edit form with phone field.
I change nothing and i click on save.

The field phone was checked as computable because into UnitOfWork in Doctrine,
because, it compare all with === 

And the two objects aren't same 
because the reference aren't the same (but the content is equals)

A temporary solution is into controller:
* Save before into `$oldPhone` the current phone
* Before flush compare `$oldPhone` and the phone into my object with `equals`
* If `equals` is true, I set the `$oldPhone` into my object

A another solution is this 
(this is a specific fix for me, i think we could be more generic with Interface on Entity use the field and detection of annotation)
```php
<?php

namespace AppBundle\Subscriber;

use Doctrine\Common\EventSubscriber;
use Doctrine\ORM\Event\PreFlushEventArgs;
use UserBundle\Entity\User;

class PhoneUpdateSubscriber implements EventSubscriber
{

    public function getSubscribedEvents()
    {
        return array(
            'preFlush',
        );
    }

    public function preFlush(PreFlushEventArgs $args)
    {
        $unitOfWork = $args->getEntityManager()->getUnitOfWork();
        $identityMap = $unitOfWork->getIdentityMap();

        if(isset($identityMap[User::class])){
            foreach($identityMap[User::class] as $user){
                $originalData = $unitOfWork->getOriginalEntityData($user);
                if($originalData['phone']->equals($user->getPhone())){
                    $user->setPhone($originalData['phone']);
                }
            }
        }
    }
}
```

What do you think of this problem ? Do you have a solution?
Can I create a PR with the last solution (but more generic ?)

Thanks

**Comment by Kreolia** [comment]
Hi,

I have the same problem, I am interessed for a solution.
Thanks.

**Comment by jewome62** [comment]
Do you try the Subscriber in my previous answer ?
It work for me

**Comment by Kreolia** [comment]
Yes, I've tried but it doesn't work for me. I think I just don't now how to adapt your code to my application.

**Comment by jewome62** [comment]
You have to adapt the getter and the setter for your field phone and change
the key "phone" by your field name

**Comment by Kreolia** [comment]
Hi,

I have another question : when your phone fields where logged several times, did you have the content of the object in your database ? In my case, the name of the field is logged but with an empty value. I think it's why it's always logged.
Thanks.

**Comment by sebdec** [comment]
Same issue here

@jewome62 the idea is not bad, but it would be better a little bit generic in the bundle
I fixed approximately the same way in my project

@Kreolia for me it adds a new log entry with the current phone number value, not an empty value

**Comment by Kreolia** [comment]
Thanks for your comment @sebdec.

I have fixed the problème with the empty value, but not the fact that phone numbers are always logged, even if they are not different.

**Comment by Kreolia** [comment]
Hi,

@sebdec, your code on the entity works absolutely fine for me. Thank you very much for your help.
