### ISSUE TITLE
Symfony Flex compatibility

### ISSUE THREAD

**Issue by teohhanhui** [misd-service-development/phone-number-bundle#149]
Specifically, check if Twig and/or Symfony Templating component is actually present.

There probably needs to be checks in place for the other components too...

**Comment by teohhanhui** [comment]
When `symfony/templating` package is not installed:

```
Fatal error: Interface 'Symfony\Component\Templating\Helper\HelperInterface' not found in /srv/example-api/vendor/misd/phone-number-bundle/Templating/Helper/PhoneNumberFormatHelper.php on line 23

09:18:20 CRITICAL  [php] Fatal Error: Interface 'Symfony\Component\Templating\Helper\HelperInterface' not found
```

**Comment by juliusstoerrle** [comment]
In this overview (https://docs.google.com/spreadsheets/d/1mFHQPp9uKtQTFjOBShIoPNHYgmkjHHdskdrd2C0BaF8/edit#gid=1730100865) there is a yes for recipe, i guess because its not needed - at least there is none listed on symfony.sh

What about registering the Doctrine DBAL Type wouldn't that be required
