### ISSUE TITLE
The "xlif" translation loader is not registered.  

### ISSUE THREAD

**Issue by leevigraham** [misd-service-development/phone-number-bundle#166]
Installing this bundle on  Symfony Version 3.4.3 I recieved the following error:

`The "xlif" translation loader is not registered.`

**Comment by julienpillias** [comment]
same error here, with SF 3.4.3 too

**Comment by iltar** [comment]
Same issue here, breaking our latest build

**Comment by rh389** [comment]
Sorry guys, a typo crept in on a file extension - this should be fixed in 1.3.2 published just now.

**Comment by iltar** [comment]
Thanks! Patching now to see if that fixes the problem :+1:

**Comment by RubenKruiswijk** [comment]
It did fix the problem for us, thanks!

**Comment by iltar** [comment]
Same here, build is passing now, thanks!

**Comment by leevigraham** [comment]
Ah I thought I checked all the file extensions :)
