### ISSUE TITLE
JMS Serializer: return empty phoneNumber: [] 

### ISSUE THREAD

**Issue by rpogorelchuk** [misd-service-development/phone-number-bundle#188]
If set JMS group 'Default' return: 
    "phone_number": {
      "country_code": 380,
      "national_number": "665286754",
      "country_code_source": 4,
      "has_number_of_leading_zeros": false,
      "number_of_leading_zeros": 1
    }
else 
 "phone_number": [],

**Comment by thebitrock** [comment]
But when i set 'Default' return >All< Entity data. (not need it)
I set 'user' group for some fields, and have phoneNumber: [].

**Comment by LanmanGroup** [comment]
i have the same problem, how did you solve?

**Comment by thebitrock** [comment]
> i have the same problem, how did you solve?

`
    /**
     * @ORM\Column(type="phone_number", nullable=true)
     * @JMS\Groups({"user"})
     * @JMS\Accessor(getter="getPhoneNumberE164")
     * @var PhoneNumber
     */
    private $phoneNumber;

    /**
     * @return null|string
     * @JMS\Groups({"user"})
     */
    public function getPhoneNumberE164(): ?string
    {
        if ($this->phoneNumber instanceof PhoneNumber) {
            $phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();

            return $phoneUtil->format(
                $this->phoneNumber,
                \libphonenumber\PhoneNumberFormat::E164
            );
        }

        return null;
    }
`
