### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by VincentLanglet** [misd-service-development/phone-number-bundle#200]
Hi @rh389 

Can you make a new release ?
I'm interested with the last commits with support for SF 3.4 and the alias `tel ->phone_number`

**Comment by DennisOluoch** [comment]
> Hi @rh389
> 
> Can you make a new release ?
> I'm interested with the last commits with support for SF 3.4 and the alias `tel ->phone_number`

waiting for the same

**Comment by Stollie** [comment]
I could use it too. I found out it wasn't working after upgrading to SF 3.4

**Comment by VincentLanglet** [comment]
Hi @rh389, can you take time to create a new release ?

Using `"misd/phone-number-bundle": "dev-master"` is not a good practice.

**Comment by VincentLanglet** [comment]
HI @rh389 Do you look for maintainers ?

**Comment by VincentLanglet** [comment]
Hi @rh389 @thewilkybarkid This library seems unmaintained. Do you need maintainers ?
