### ISSUE TITLE
Is this bundle abandoned?

### ISSUE THREAD

**Issue by shtumi** [misd-service-development/phone-number-bundle#226]
Last merged commit is more then 2 years ago.
There are pull requests to support Symfony 5 and twig 3, but not merged.
Is this bundle abandoned?

**Comment by xabbuh** [comment]
FYI: #217

**Comment by rh389** [comment]
Short answer, it has been, but hopefully not any more. See [my response here](https://github.com/misd-service-development/phone-number-bundle/issues/217#issuecomment-756820940).
