### ISSUE TITLE
Add missing phonenumber types to validator constraint

### ISSUE THREAD

**Issue by JHGitty** [misd-service-development/phone-number-bundle#35]
Add these missing phonenumber types to /Validator/Constraints/PhoneNumber.php

<s>FIXED_LINE_OR_MOBILE</s> (edit: doesn't make sense.)
PAGER
PERSONAL_NUMBER
PREMIUM_RATE
SHARED_COST
TOLL_FREE
UAN
VOIP

Source of all types: https://libphonenumber.googlecode.com/svn/trunk/javadoc/com/google/i18n/phonenumbers/PhoneNumberUtil.PhoneNumberType.html

**Comment by Cartman34** [comment]
Hi,
These missing features are very annoying, please, could you fix it ? I really need that voip is available... they are used as fixed_line (in France) !
It will be perfect if it could allow multiple type seperate by coma or an array ?

**Comment by JHGitty** [comment]
@thewilkybarkid I only can see VOIP but not VoiceMail in the above link. Where did you get the information about "VoiceMail"?
