### ISSUE TITLE
use buildViolation

### ISSUE THREAD

**Issue by rafaelschmitt** [misd-service-development/phone-number-bundle#37]
Hello,
currently you are using `addViolation` in your https://github.com/misd-service-development/phone-number-bundle/blob/master/Validator/Constraints/PhoneNumberValidator.php#L98
So there is no option to set an `atPath` where to display the message! you not even use `addViolationAt`

However, `addViolation` and `addViolationAt` are deprecated from symfony 2.5 and will be removed at 3.0. You should use `buildViolation()` instead.
http://symfony.com/doc/current/cookbook/validation/custom_constraint.html#creating-the-validator-itself

You can do something like this:
in Validator/Constraints/PhoneNumber.php

``` bash
class PhoneNumber extends Constraint
{
    public $message = 'This value is not a valid {{ type }} number.';
    public $type = 'phone';
    public $defaultRegion = PhoneNumberUtil::UNKNOWN_REGION;
    public $atPath = 'anyProperty';
}
```

in Validator/Constraints/PhoneNumberValidator.php
instead of

``` bash
private function addViolation($value, Constraint $constraint)
    {
        $this->context->addViolation(
            $constraint->message,
            array('{{ type }}' => $constraint->type, '{{ value }}' => $value)
        );
    }
```

you can use the new function

``` bash
private function addViolation($value, Constraint $constraint)
    {
        $this->context->buildViolation($constraint->message)
            ->atPath($constraint->atPath)
            ->setParameter('{{ type }}', $constraint->type)
            ->addViolation();
    }
```

or instead of directly accessing the $constraint properties (e.g. $constraint->atPath) use
a function (saw now that you already did it with getter functions)

``` bash
public function getAtPath()
```

With this changes you are save for the future (symfony 3.0+) and you give an option to set the atPath property, so the user can determine where the violation message should appear.

**Comment by thewilkybarkid** [comment]
The bundle supports versions before 2.5 (ie 2.3) so can't use `buildViolation()` yet. Future versions can do.

Regarding the path, this sounds like #19.

**Comment by xabbuh** [comment]
@thewilkybarkid You could do the `buildValidation()` call conditionally (depending on the installed version of the Validator component).

**Comment by rafaelschmitt** [comment]
@thewilkybarkid ok i understand, you are right. Then the idea of xabbuh could be a solution.
Or you could maybe then replace `addViolation` with `addViolationAt` and do so:

```bash
private function addViolation($value, Constraint $constraint)
    {
        $this->context->addViolationAt(
            $constraint->atPath,
            $constraint->message,
            array('{{ type }}' => $constraint->type, '{{ value }}' => $value)
        );
    }
```

It would be really nice if you would give an option to decide where the violation message should appear.

**Comment by JHGitty** [comment]
@thewilkybarkid What's about a master-branch for Symfony 2.7+, 2.8+ or 3.0+ and a current stable branch for the current code? Then you could use these new features.

**Comment by mablae** [comment]
Interesting. @xabbuh  can you give an example how such a version check would be done proplery?

**Comment by xabbuh** [comment]
@mablae You can check if the `Symfony\Component\Validator\Context\ExecutionContextInterface` interface does exist (which was introduced in Symfony 2.5):

```php
if (interface_exists('Symfony\Component\Validator\Context\ExecutionContextInterface')) {
    // Symfony 2.5 or higher
} else {
    // Symfony before 2.5
}

**Comment by ste93cry** [comment]
I've prepared a PR to fix this issue. I had to adapt the code to work both for `Symfony < 2.5` and `Symfony 2.5+`. Raising the requirements of Symfony to at least `2.7` which is LTS would help with future tickets too and would make life easier because we could simplify some parts of the code that are now a real mess, e.g. the unit tests that have to handle different `ExecutionContext` classes (I don't remember in which version it was added but I know that there is now a documented trait to use for the unit tests of a validator that should handle all cases).

**Comment by ste93cry** [comment]
ping @thewilkybarkid any news on this? PR is ready to be reviewed

**Comment by ste93cry** [comment]
ping @thewilkybarkid any news on this? PR is ready to be reviewed

**Comment by ste93cry** [comment]
ping @rh389 can we please move forward on this if it's still valid?

**Comment by rh389** [comment]
https://github.com/misd-service-development/phone-number-bundle/pull/108 is now merged, so closing this.
