### ISSUE TITLE
Question: Can the bundle support multiple regions?

### ISSUE THREAD

**Issue by kcaporaso** [misd-service-development/phone-number-bundle#39]
It seems I'm forced to set a default region in order to get phone numbers to persist.  
However, if I set my form builder element with a default_region => 'US',  format=> PhoneNumberFormat::INTERNATIONAL I'm not allowed to enter and save international phone numbers.  e.g. it'll take: 800-800-2775  (US phone number) but not: 0451 029 226 (an Australian phone number).  So is it expected that I have to fall into one region with this bundle or have I missed something? My specific application needs to accept phone numbers from around the globe.

Thanks!

**Comment by kcaporaso** [comment]
Ping... wondering if anyone is actively maintaining this bundle?  Thanks!

**Comment by selossevianney** [comment]
I'm in the same case, so if someone can give you an answer it would be wonderful. I reported this issue in the giggsey repo, maybe you can try there. 

Have you resolved your problem or found an alternative solution?

**Comment by giovkanata** [comment]
With ```use libphonenumber\PhoneNumberUtil;``` and ```'default_region' => PhoneNumberUtil::UNKNOWN_REGION``` you are able to insert any international number.

**Comment by selossevianney** [comment]
when I specify the parameter like this, it doesn't work, I can't persist the datas.

**Comment by thewilkybarkid** [comment]
@kcaporaso Sorry for not looking at this sooner. It sounds like #24 will be what you're after.
