### ISSUE TITLE
Mobile type format for MD region

### ISSUE THREAD

**Issue by ruscon** [misd-service-development/phone-number-bundle#44]
show
+373 681 11 111

must be
+373 68 111 111

**Comment by giggsey** [comment]
Hi,

If you try this number in one of the libphonenumber demos ([PHP version](http://giggsey.com/libphonenumber/?phonenumber=%2B373+681+11+111&country=GB&language=&region=) or [Google's parent version](http://libphonenumber.appspot.com/)), you will see that it formats the number like your first example.

If you believe this is a bug with the formatting of the number, you'll need to report it to Google at https://github.com/googlei18n/libphonenumber

**Comment by ruscon** [comment]
Ok, thx

**Comment by xabbuh** [comment]
FYI, see googlei18n/libphonenumber#632
