### ISSUE TITLE
Validator with french numbers

### ISSUE THREAD

**Issue by selossevianney** [misd-service-development/phone-number-bundle#45]
It seems that the validator refuse to validate mobile phones that begin with 07 in france. 
In france, mobile phones begin with 06 or 07.

**Comment by chadyred** [comment]
French fixed line number begin with 09, this bundle doesn't handle that.

**Comment by selossevianney** [comment]
For my problem, it was just that I was testing wrong 07 numbers , I didn't know that french 07 numbers are valid only if the next number was 5 minimum . Are you sure you tested a valid 09 phone number ? Try with a real exemple.

**Comment by chadyred** [comment]
You're right: 
on my Form, the 'default_region' => 'FR', 'format' => PhoneNumberFormat::NATIONAL works perfect, but with 
<pre>
     * @AssertPhoneNumber(defaultRegion="FR")
     * @AssertPhoneNumber(type="fixed_line")
</pre>

 the number is not working AT ALL!

**Comment by giggsey** [comment]
@chadyred Looking at the actual data it uses to validate, it appears that 09 numbers from France are VoIP. Fixed Line numbers appear to match `[1-5]\\d{8}`

https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/data/PhoneNumberMetadata_FR.php

**Comment by thewilkybarkid** [comment]
Closing as this seems to be an upstream (data) issue rather than with the bundle.
