### ISSUE TITLE
Dynamically pass "defaultRegion"

### ISSUE THREAD

**Issue by dbhattacharjee** [misd-service-development/phone-number-bundle#59]
Hi,
In my use case, users can be from many country and each country may have its own phone number format. How I can pass "defaultRegion" dynamically based upon user's country?

**Comment by JHGitty** [comment]
Good question. Would also be helpful for me because the user should be allowed to change the default region. For example the user has a ``phone_number`` input field where he is allowed to add a national number. If he is from Germany he will enter a german number as national number, etc. :smile:

**Comment by dbhattacharjee** [comment]
Ended up by doing this :
```
return $contactNumber!= '' ? $kernel->getContainer()->get('libphonenumber.phone_number_util')
               ->parse($contactNumber, $countryCode, null, true) : NULL;
```

**Comment by thewilkybarkid** [comment]
Closing this as `default_region` is an option on the form type. Please reopen if this is still an issue.
