### ISSUE TITLE
Status of this bundle

### ISSUE THREAD

**Issue by erichard** [misd-service-development/phone-number-bundle#63]
Hello,

What is the current status of this bundle ? Is it still maintained ? 
No commit since May and many PR are opened...

**Comment by JHGitty** [comment]
Good question! If it is not maintained anymore it would be great to get a official response for it.

**Comment by Rvanlaak** [comment]
:+1:

**Comment by Rvanlaak** [comment]
:+1: ping @thewilkybarkid

**Comment by erichard** [comment]
I'll wait a little more but without response I think the best move is to fork this bundle.

**Comment by erichard** [comment]
Fork has started at https://github.com/le-phare/phone-number-bundle.
Current PR will be merged soon.

**Comment by Rvanlaak** [comment]
You know this bundle already has 111k of installs on Packagist? https://packagist.org/packages/misd/phone-number-bundle

So, don't know or forking is the best way to go. 

Did send @thewilkybarkid an email, so hope he'll reply.

**Comment by erichard** [comment]
@Rvanlaak Thank. I hope so.

**Comment by JHGitty** [comment]
@Rvanlaak Is there any guideline what to do if a widely used package is not maintained anymore and the developers itself is not responding?

**Comment by erichard** [comment]
@Rvanlaak Did @thewilkybarkid answer your mail ?

**Comment by Rvanlaak** [comment]
No response, really weird because @thewilkybarkid did some contributions lately as you can see in it's profile.

**Comment by xabbuh** [comment]
I contacted him a while ago too and didn't get a response either. :(

**Comment by JHGitty** [comment]
Is there any way to add a warning that this package is not maintained anymore on Packagist?
https://packagist.org/packages/misd/phone-number-bundle

Like on this bundle:
https://packagist.org/packages/zenstruck/slugify-bundle

**Comment by erichard** [comment]
@JHGitty I think only the author can change the flag (https://github.com/composer/packagist/issues/192). 

But maybe we can contact the packagist team in case of abandonned packages.

**Comment by Rvanlaak** [comment]
If I remember correctly from some issues I was following @Seldaek should do this manually.

**Comment by Seldaek** [comment]
I could do it but if there is no alternative to point people at it's kinda pointless to just say it's abandoned no? I'll email him real quick as well.

**Comment by erichard** [comment]
@Seldaek Thanks for your reply. What is the best move in this case ? Should we fork and keep the package name or fork and rename ?

**Comment by Seldaek** [comment]
I'd wait a bit.. See if the original maintainer gets back on track or at
least gives commit access to someone else. If not then I'd say fork and
rename and i can mark it abandoned so people get told to move to the fork.
But that's a last resort I rather avoid.

**Comment by Rvanlaak** [comment]
Generally speaking; maybe the abandon message is something that can be shown by composer while doing `composer update`?

**Comment by xabbuh** [comment]
@Rvanlaak Isn't that already the case? I remember getting such a warning in the past when using an abandoned package.

**Comment by thewilkybarkid** [comment]
Sorry for the silence round here, I left the company that this was licensed through during the summer. I've been in touch to try and resolve it's future one way or another (ie carrying it on, or forking it). Hopefully this will be resolved soon (I am happy to get things back up to speed and maintain it; while I won't be using it myself in the near future, I know it is useful).

(@xabbuh, sorry for not replying, I did get your email while I was away and completely forgot about it when I got back. @rvanlaak, sorry for not replying either, I suspect you sent it to my old work address which is on the README, I've mentioned removing this too.)

**Comment by rvanlaak** [comment]
What about adding extra maintainers, that would be the quickest solution :+1:

**Comment by JHGitty** [comment]
@thewilkybarkid No problem. The most important thing is your answer. Would be great if you could find an extra maintainer or fork it.

If it will result in a fork there should be a deprecation warning added to Packagist. Packagist added support for this in the future. There you can add a message which library instead should be used. This would be really helpful for the users.

**Comment by JHGitty** [comment]
@thewilkybarkid Any updates? We really need to update this bundle to Symfony3.

**Comment by thewilkybarkid** [comment]
Good news, I have permission to carry it on as is. I'll go through open issues and merge in bug fixes/Symfony 3 support in the next couple of days, then start to look at new features.

**Comment by JHGitty** [comment]
Yeah, thanks! This bundle is really really helpful in a lot of applications.

**Comment by VincentLanglet** [comment]
No commit since last year, is this bundle this maintained ? Do you look for maintainers ?
