### ISSUE TITLE
Phone to String is not available?

### ISSUE THREAD

**Issue by robhunt3r** [misd-service-development/phone-number-bundle#64]
So I would like to know if there's a way to transform PhoneNumber to string with prefix, for example

+34600000000 for Spain, because when using a PhoneNumber inside query it's not returning anything because MySQL has `+34600000000` and PhoneNumber doesn't add the +34 prefix in any way (not even getNationalNumber) so it is useless...

I know that you can instance the utils, parse/transform etc but man, there should be just a one liner way to do it inside the class itself.

Something like this inside `PhoneNumber` class

`
public function getStringNumber()
{
    return sprintf("+%d%d", $this->getCountryCode(), $this->getNationalNumber());
}
`

So easy...

**Comment by JHGitty** [comment]
Why you do not use the ``getStringNumber()`` function if it is exactly what you want?

**Comment by JHGitty** [comment]
Could you provide some code to show where you exactly need help?

**Comment by giggsey** [comment]
@robhunt3r Don't you just want to format it to E164, and search for that?

Also, doing a straight toString of `+[Country Code][National Number]` may seem like it's converting it to E164, but there are some countries with exceptions. (See https://github.com/giggsey/libphonenumber-for-php/issues/75 for an example)

**Comment by thewilkybarkid** [comment]
Closing this as it's one for the libphonenumber library.
