### ISSUE TITLE
Support Symfony 3

### ISSUE THREAD

**Issue by geekdevs** [misd-service-development/phone-number-bundle#65]
Please add support for symfony3

**Comment by JHGitty** [comment]
+1 :+1:

**Comment by rafaelschmitt** [comment]
+1

**Comment by Zeichen32** [comment]
:+1:

**Comment by JHGitty** [comment]
Maybe we only need to do this: https://github.com/mkrauser/phone-number-bundle/commit/1d71d935b9c84c597723742b9b6d856e0bf2dd65
But we are not sure yet if anything else is needed.

Please write it here if it works fine with Symfony 3.0+ without other changes.

To check it just do this in the ``composer.json`` file:
```json

  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/mkrauser/phone-number-bundle"
    }
  ],

  "require": {
    "misd/phone-number-bundle": "dev-master",
  },
```

**Comment by JHGitty** [comment]
There are some Travis CI build errors:
https://github.com/misd-service-development/phone-number-bundle/pull/66

Hopefully somebody will fix it. :smile:

**Comment by thewilkybarkid** [comment]
v1.0.6 has been released.
