### ISSUE TITLE
[Travis CI] Check multiple Symfony versions

### ISSUE THREAD

**Issue by JHGitty** [misd-service-development/phone-number-bundle#72]
The Travis CI should always check against multiple Symfony versions. Currently it only check against the newest version.

I think we should check it against Symfony 2.3 (LTS) and Symfony 2.8 (LTS). Symfony 3.0 could be added once the compatibility of Symfony 3 has been merged into the ``master`` branch.

**Comment by thewilkybarkid** [comment]
It checks against the newest and oldest, but it would be good to check the latest 2.x at least.
