### ISSUE TITLE
Fix doctrine phpdoc auto generation

### ISSUE THREAD

**Issue by JHGitty** [misd-service-development/phone-number-bundle#73]
**Edit:** Known issue in Doctrine2: https://github.com/doctrine/doctrine2/issues/4911

I have this code in my entity:
```php
/**
 * @var PhoneNumber
 *
 * @ORM\Column(type="phone_number")
 */
private $number;
```

Currently doctrine generates this:
```php
/**
 * Set number
 *
 * @param phone_number $number
 *
 * @return ContactPhone
 */
public function setNumber($number)
{
    $this->number = $number;

    return $this;
}

/**
 * Get number
 *
 * @return phone_number
 */
public function getNumber()
{
    return $this->number;
}
```

As you can see the phpdoc is wrong. It should not be ``phone_number``.
Instead ``\libphonenumber\PhoneNumber`` would be right.

Does anybody have an idea how to fix that? It also works with ``datetime`` => ``\DateTime``. Why and how?

**Comment by xabbuh** [comment]
Do you import the `PhoneNumber` class with a `use` statement?

**Comment by JHGitty** [comment]
Sure.

```php
use libphonenumber\PhoneNumber;
```
```bash
> C:\xampp\php\php.exe bin/console doctrine:generate:entities AppBundle:ContactPhone
Generating entity "AppBundle\Entity\ContactPhone"
  > backing up ContactPhone.php to ContactPhone.php~
  > generating AppBundle\Entity\ContactPhone
```

```php
* @param phone_number $number
```
```php
* @return phone_number
```

**Comment by xabbuh** [comment]
Looks like this is related to Doctrine then and should be reported there.

**Comment by JHGitty** [comment]
But how it works with the ``DateTimeType`` (``\DateTime``)?

**Comment by mbabker** [comment]
In the [EntityGenerator](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/EntityGenerator.php) there's a map of Doctrine types mapped to PHP types and it has the mapping for `\DateTime` in it.  Unfortunately it doesn't look like there's an API in that class to add anything to the mapping.

**Comment by JHGitty** [comment]
Known issue in Doctrine2: https://github.com/doctrine/doctrine2/issues/4911

**Comment by thewilkybarkid** [comment]
Closing as it's a Doctrine issue.
