### ISSUE TITLE
Undefined class constant 'WIDGET_COUNTRY_CHOICE'

### ISSUE THREAD

**Issue by iBasit** [misd-service-development/phone-number-bundle#74]
I can't find 'WIDGET_COUNTRY_CHOICE' at all. following error I get.

Error: Undefined class constant 'WIDGET_COUNTRY_CHOICE'

```php
use libphonenumber\PhoneNumberFormat;
use Misd\PhoneNumberBundle\Form\Type\PhoneNumberType;
use Symfony\Component\Form\FormBuilderInterface;

public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('phone_number', 'tel', array('widget' => PhoneNumberType::WIDGET_COUNTRY_CHOICE, 'country_choices' => array('GB', 'JE', 'FR', 'US'), 'preferred_country_choices' => array('GB', 'JE')));
}
```

**Comment by xabbuh** [comment]
Which version of the bundle do you use?

**Comment by iBasit** [comment]
v1.0.6

**Comment by xabbuh** [comment]
The constants are not part of any stable release yet.

**Comment by iBasit** [comment]
It's on documentation.

**Comment by giovkanata** [comment]
@iBasit  the linked documentation refers to the "master" branch (dev version).

**Comment by thewilkybarkid** [comment]
`v1.1.0` will be released soon (should be this week).

**Comment by iBasit** [comment]
Looking forward.

**Comment by iBasit** [comment]
@thewilkybarkid I been waiting for this release :+1:

**Comment by iBasit** [comment]
Sorry, I don't want to seem like I'm pushing on this, but its been 2 weeks. Just waiting on the release, so I can add this feature on our application :)

Thanks for all the hard work you guys did.

**Comment by iBasit** [comment]
Just wanted to bump this release, if someone can make it happen :)

**Comment by iBasit** [comment]
Thank you for the release.
