### ISSUE TITLE
FIX phone_number mapping

### ISSUE THREAD

**Issue by robhunt3r** [misd-service-development/phone-number-bundle#79]
So when using mapping like in the docs, and telling my field to be a  `phone_number` type, I get this error

`Expected AppBundle\Entity\phone_number got \libphonenumber\PhoneNumber`

when calling `$entity->setPhone($phone);`

this is how I create my `$phone`

`$phone = $container->get('libphonenumber.phone_number_util')->parse($string, PhoneNumberUtil::UNKNOWN_REGION);`

for example.

Needless to say that this constant warnings makes all my code "non ok" at the eyes of the IDE, and sometimes is a mess because you forgot about this bug...

**Comment by xabbuh** [comment]
Can you show the code of your entity class?

**Comment by mbabker** [comment]
If you're using SensioGeneratorBundle or Doctrine's entity generator to generate your code, you'll still have to make some manual edits.  The `phone_number` type doesn't get mapped correctly in Doctrine (see https://github.com/misd-service-development/phone-number-bundle/issues/73 and referenced links) so you'll need to change the typehints to reference the correct object types.

**Comment by robhunt3r** [comment]
Yeah, that's what I thought... It should map the class referenced in our config for `phone_number` thanks

**Comment by thewilkybarkid** [comment]
Closing as this is a Doctrine issue.
