### ISSUE TITLE
libphonenumber\PhoneNumberUtil::format() must be an instance of libphonenumber\PhoneNumber, string given

### ISSUE THREAD

**Issue by fernandopg** [misd-service-development/phone-number-bundle#8]
I'm using the PhoneNumberBundle with Doctrine, I have this field:

```
/**
 * @ORM\Column(type="phone_number", nullable=true)
 * @Serializer\Type("libphonenumber\PhoneNumber")
 * @AssertPhoneNumber(defaultRegion="US")
 */
protected $phoneNumber;
```

The validation is ok, but when I persist the object I get this error:

Catchable Fatal Error: Argument 1 passed to libphonenumber\PhoneNumberUtil::format() must be an instance of libphonenumber\PhoneNumber, string given, called in /miproject/vendor/misd/phone-number-bundle/Misd/PhoneNumberBundle/Doctrine/DBAL/Types/PhoneNumberType.php on line 58 and defined in /myproject/vendor/giggsey/libphonenumber-for-php/src/libphonenumber/PhoneNumberUtil.php line 992

I debugged the code and I saw that in class PhoneNumberType, the function convertToDatabaseValue receives the string and not the libphonenumber\PhoneNumber object...

Should I parse and create the libphonenumber\PhoneNumber before persist the object?

Thanks!

**Comment by Bukashk0zzz** [comment]
@thewilkybarkid Thanks you.
