### ISSUE TITLE
Use libphonenumber\PhoneNumber object in DQL

### ISSUE THREAD

**Issue by snoop168** [misd-service-development/phone-number-bundle#80]
Have a repository method that takes the PhoneNumber object as an argument. I have my dql query written as:

        ->createQuery(
            'SELECT p, m FROM AppBundle:Phone p JOIN p.member m WHERE p.phoneNumber = :phone AND m.allowFind = TRUE'
        )
        ->setParameter("phone", $phone)
        ->getOneOrNullResult();

However when it generates the query it puts `'Object(libphonenumber\PhoneNumber)'` where I would expect it to actually put the Phone Number in the format `+1##########`

When I use the default findOneByPhoneNumber($phone) it generates the query fine.

**Comment by snoop168** [comment]
figured it out.. retrieved the E164 format by doing the following:

       $phoneNumberUtil = PhoneNumberUtil::getInstance();
       $number = $phoneNumberUtil->format($phone, \libphonenumber\PhoneNumberFormat::E164); 

then passed $number into the `setParameter()` method instead of `$phone`

**Comment by skylord123** [comment]
I ran into this same problem and it's because you need to pass the third option to `setParameter` for the type `phone_number`.

Example:

```
    public function countWithPhone(PhoneNumber $phone): int
    {

        $qb = $this->createQueryBuilder('c');
        $qb->select('COUNT(c.id)')
            ->andWhere($qb->expr()->eq('c.phone', ':phone'))
            ->setParameter('phone', $phone, 'phone_number');
        return $qb->getQuery()->getSingleScalarResult() ?? 0;
    }
```

This is better than having to do the formatting yourself. Leaving this here in hopes it helps someone else out.
