### ISSUE TITLE
Removing Phone Number with Widget

### ISSUE THREAD

**Issue by pculka** [misd-service-development/phone-number-bundle#81]
If I have a Country Widget in my form, how can I remove phone number from my profile?
There is no option to have an empty value in the country field(!), therefore it is impossible to properly remove the phone number from the entity

**Comment by pculka** [comment]
well, made a PR #82

**Comment by thewilkybarkid** [comment]
I think there's two options here:

1. Allow the number to be empty when the field isn't required (ie the country option still has a value)
2. Create an empty country option when the field isn't required.
