### ISSUE TITLE
Can't Use PhoneNumberType::WIDGET_COUNTRY_CHOICE without hitting an error (Array to string conversion)

### ISSUE THREAD

**Issue by prindacerk** [misd-service-development/phone-number-bundle#83]
I camr across this bundle and I am trying to integrate it into my application. I have followed all the notations and the database was created as mentioned in the documentation.

My environment is PHP 7 and Symfony 3.

However, I encountered a couple of issues.

1) "tel" form type doesn't work. Instead I had to use PhoneNumberType::class as the form type in my form setup.
2) Country choice fields doesn't work. I copied the same line and tried to use it and I get this error.
`An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in form_div_layout.html.twig at line 13.`

This line works.
`->add('landlineNo', PhoneNumberType::class, array('default_region' => 'GB', 'format' => PhoneNumberFormat::NATIONAL))`

This line doesn't.
`->add('landlineNo', PhoneNumberType::class, array('widget' => PhoneNumberType::WIDGET_COUNTRY_CHOICE, 'country_choices' => array('GB', 'JE', 'FR', 'US'), 'preferred_country_choices' => array('GB', 'JE')))`

Is there any suggestion on how to resolve this so I can use the Country dropdown? Or do I need to append the country code manually?

Would really appreciate a fix since I am trying to get this form done and phone number is the only one pending.

**Comment by thewilkybarkid** [comment]
Re 1, this is a change between Symfony 2 and 3, the doc needs updating.

Re 2, I've just created a fresh Symfony standard-edition project, added a simple form with those fields and it works... What version of Symfony and the bundle are you using? Can you provide some more details where the array to string conversion is happening? (eg file/line number, what value etc)

**Comment by prindacerk** [comment]
Regarding 2nd,
Symfony version: "3.0.*"
Phone-Number-Bundle version: "1.1.x-dev"

Entity Class Attribute


	 /**
	 * @var \libphonenumber\PhoneNumber
	 *
	 * @AssertPhoneNumber(type="FIXED_LINE")
	 *
	 * @Type("libphonenumber\PhoneNumber")
	 *
	 * @ORM\Column(name="landline_no", type="phone_number", nullable=true)
	 */
	private $landlineNo;`

Class Type Form
`->add('landlineNo', PhoneNumberType::class, array('widget' => PhoneNumberType::WIDGET_COUNTRY_CHOICE))`


Error Message
`An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in form_div_layout.html.twig at line 13.`

I don't understand the error since I am not setting any values and it is a fresh form (new account I am trying to create). From what I can tell, when I add the **WIDGET_COUNTRY_CHOICE** option, it is throwing an error. Without it, it works fine.

`->add('landlineNo', PhoneNumberType::class, array('default_region' => 'GB'))`

So only conclusion I came to was that this country choice was what was throwing the error. I didn't do any customization to the Type or Form.

**Comment by thewilkybarkid** [comment]
To clarify, the error is happening on:

```twig
<input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
```

isn't it?

Could you debug what those values are? (ie which one is an array, and which one is it, and ideally where is it coming from)

**Comment by prindacerk** [comment]
The ContextErrorException shows different code.

        echo " ";
        if ( !twig_test_empty((isset($context["value"]) ? $context["value"] : $this->getContext($context, "value")))) {
            echo "value=\"";
            echo twig_escape_filter($this->env, (isset($context["value"]) ? $context["value"] : $this->getContext($context, "value")), "html", null, true);
            echo "\" ";
        }
        echo "/>";

The yellow highlighted line is from 

> echo twig_escape_filter($this->env, (isset($context["value"]) ? $context["value"] : $this->getContext($context, "value")), "html", null, true);

**Comment by thewilkybarkid** [comment]
That's compiled Twig. It shows the problem is with the `value` of whichever field that is (I'm assuming it's the number field). Can you debug to find out what the value is?

**Comment by prindacerk** [comment]
I am not setting a value. It is an empty value for that textbox. 

Would a full stacktrace help you? I am at a loss on how to debug this because the Type gets rendered in twig and I don't know how to debug that.

If not, kindly guide me on how to debug this.

**Comment by prindacerk** [comment]
I sincerely apologize @thewilkybarkid . The issue is not with your bundle but my mistake. It seems that the HTML5 type 'tel' styling from another part of my code was affecting your component rendering. Both had the same block name ("tel_widget"). So instead of rendering your control using your template, it was using this template. And since that HTML5 template was a simple textbox, it was hitting the error.

Once again, I apologize for the trouble and appreciate your good work. Keep it up and I look forward to more development work from you that will help people like me.

**Comment by thewilkybarkid** [comment]
No problem @prindacerk, glad you were able to solve it!

**Comment by prindacerk** [comment]
If you don't mind me suggesting, it would be better to rename the name of the type and use that in the twig instead of 'tel'. Reason being that 'tel' is a common name and it may conflict again when other template also uses the same name.

**Comment by K0rell** [comment]
Hey, @thewilkybarkid 

Same error for me after symfony upgrade 3.2 => 3.4

Now i'am using symfony 3.4 with Twig bridge 3.4

And the new 'form_div_layout.html.twig' template use 'tel_widget' block name. So i think a new name for the misd "tel_widget" is needed !

When remove 'tel_block' in the vendor file everything is ok !

https://github.com/symfony/twig-bridge/blob/b3431c9214e3d386e53e16d63d716a85e8635e03/Resources/views/Form/form_div_layout.html.twig#L242

**Comment by K0rell** [comment]
You can use this solution in your twig template.

```twig
{% block content %}
    {% form_theme form with ['MisdPhoneNumberBundle:Form:tel_bootstrap.html.twig'] %}

    {{ form_start(form) }}
        {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}
```

**Comment by 1988gadocansey** [comment]
This doesn't work in symfony4
{% block content %}
    {% form_theme form with ['MisdPhoneNumberBundle:Form:tel_bootstrap.html.twig'] %}

    {{ form_start(form) }}
        {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

**Comment by JusteLeblanc** [comment]
I have the same issue when upgrading to Symfony 3.4 version.
We are using SonataAdminBundle, and I can't fix the issue for our admin pages.
@thewilkybarkid do you plan to change the widget name so that we can use the lib with Symfony 3.4 form_div_layout ?

Many thanks

**Comment by iBasit** [comment]
no one is fixing this lol — This lib should not be used in prod anymore.

**Comment by chokrijobs** [comment]
it works form me
```php
use Misd\PhoneNumberBundle\Form\Type\PhoneNumberType;

class CustomPhoneNumberType extends PhoneNumberType
{
    public function getBlockPrefix()
    {
        return 'custom_tel';
    }

}
```
and add widget YourBundle:Form:custom_tel_widget.html.twig:
```twig
{% block custom_tel_widget -%}
    {% if widget is constant('Misd\\PhoneNumberBundle\\Form\\Type\\PhoneNumberType::WIDGET_COUNTRY_CHOICE') %}
        {% set attr = attr|merge({class: (attr.class|default('') ~ ' form-inline')|trim}) %}
        <div {{ block('widget_container_attributes') }}>
            {{- form_widget(form.country) -}}
            {{- form_widget(form.number) -}}
        </div>
    {% else -%}
        {{- block('form_widget_simple') -}}
    {%- endif %}
{%- endblock custom_tel_widget %}

```
config.yml
```yaml
twig:
    ...
    form_themes:
        - ..
        - 'YourBundle:Form:custom_tel_widget.html.twig'
```

**Comment by numediaweb** [comment]
@chokrijobs solution worked for me. Thanks!

**Comment by chokrijobs** [comment]
@numediaweb thank you too

**Comment by JusteLeblanc** [comment]
@numediaweb @chokrijobs no need to do so as this PR https://github.com/misd-service-development/phone-number-bundle/pull/175 should have fixed the issue. Could you confirm it to me ?

**Comment by chokrijobs** [comment]
@JusteLeblanc it works

**Comment by flopp26** [comment]
@chokrijobs thanks you for your solution ;-)

**Comment by MatthieuPoullin** [comment]
@1988gadocansey for symfony 4 you can use
`{% form_theme form '@MisdPhoneNumber/Form/tel_bootstrap.html.twig' %}`
