### ISSUE TITLE
Making Phone Number field Optional

### ISSUE THREAD

**Issue by prindacerk** [misd-service-development/phone-number-bundle#85]
I am trying to get the fields to be optional instead of mandatory (most people won't fill both Landline and Mobile). However, even if I set the field to be optional, the form isValid() fails because of this field.

Kindly assist in figuring out how to make it optional. I don't have any of my own validator configured. So it is basically what Symfony validators are working with.

My class field variable below. As you can see, **nullable=true** so database can accept null value.

	 * @var \libphonenumber\PhoneNumber
	 *
	 * @Type("libphonenumber\PhoneNumber")
	 *
	 * @ORM\Column(name="landline_no", type="phone_number", nullable=true)
	 */
	private $landlineNo; 

My Type for the field. I have set **required => false**.

`->add('landlineNo', PhoneNumberType::class,
						array(
								'widget' => PhoneNumberType::WIDGET_COUNTRY_CHOICE,
								'preferred_country_choices' => array("GB", "US", "AU"),
								'label' => "Landline No",
								'required' => false,
						)
				)`

But when I submit the form, it is returning back as invalid because of the missing value.

Would appreciate the guidance to get this done right.

**Comment by alphatesla** [comment]
release 1.1.2 fixes the problem for me ! Thx!
