### ISSUE TITLE
placeholder on phone number

### ISSUE THREAD

**Issue by iBasit** [misd-service-development/phone-number-bundle#96]
I'm displaying form without labels, but using placeholder has labels.

I have been trying to search and use different method to put placeholder for phone, but it puts it on div element and not the input. How can I put placeholder on input field of phone number?

**Comment by iBasit** [comment]
```

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        if (isset($view['phone']))
            $view['phone']->children['n
```umber']->vars['attr']['placeholder'] = 'Phone';
    }

**Comment by terox** [comment]
For PhoneNumberType::WIDGET_SINGLE _TEXT we should use in ```finishView```:

```php
$view['phoneNumber']->vars['attr']['placeholder'] = 'Phone';
```
